### ISSUE TITLE
Reviewing readme for typos and general copy quality

### ISSUE THREAD

**Issue by 1egoman** [1egoman/biome#11]
Biome's readme has gone through a number of iterations. Its hard to explain how Biome works to someone for the first time. I'd really love it if someone could go over the readme and do a few things:

- Fix any typos
- A quick retrospective - What is confusing? What makes a lot of sense? Are there any questions to add to FAQ?
- If you think you know how to make the readme more clear, go for it!

Thanks!

**Comment by chirag08** [comment]
I am reviewing it

**Comment by 1egoman** [comment]
Thanks a lot @chirag08! Feel free to make a pull request with any changes you think I should make.

**Comment by chirag08** [comment]
Kindly Review PR - #15

**Comment by 1egoman** [comment]
Also tackled in #16 !

**Comment by 1egoman** [comment]
Thanks everyone for the help!
