### ISSUE TITLE
Biome should style the prompt inside of a biome use "context"

### ISSUE THREAD

**Issue by 1egoman** [1egoman/biome#13]
When a user runs `biome use`, they are able to to enter a new environment. Right now, the prompt looks exactly the same as it does outside the environment, which causes some confusion. I'm thinking the the prompt should be prefixed with the environment they are in. Here's am example:

```
[the user's custom fancy prompt] $ biome use
(the new environment) [the user's custom fancy prompt] $ # the user is now in the environment
```

Here's the magic line that injects the variables into the environment: `bash -c "$(cat $PROJECT_PATH) && $SHELL -l"`

Most likely, all that would be required here is prepending the contents of `$PROJECT` (within the bash script) to the `$PS1`. If all else fails, I know [virtualenv](https://github.com/pypa/virtualenv) does this so you see how they do it.

If you'd like any clarification, feel free to ping me. Thanks!

**Comment by joesavage** [comment]
Taking a quick look at this, it turns out to be a little more difficult than it seems. As `biome use` spawns a subshell, this is likely to trigger a configuration script such as `.bashrc` which may reset the `PS1` variable. So simply setting `PS1` before creating the subshell will often not work as expected (I believe virtualenv gets around this as it doesn't actually invoke a subshell).

**Comment by merkkp** [comment]
I tried to:

1. Pass a ```<(export PS1='[$PROJECT] $PS1')``` to ```--rcfile``` option, but the ```-l``` login option overwrites it, also it doesn't work in zsh, as it doesn't has the ```--rcfile``` option.

2. Evaluate in the subshell something like ```export PS1=[$PROJECT] $PS1``` using the variables from the parent shell. But I still haven't figured it out how to do it.

Maybe later I'll try to have another look at this with a different approach. :)

**Comment by 1egoman** [comment]
@joesavage @merkkp It's good to know that I'm not the only one who was having problems setting this up. 😄 

It looks like using `PS1` won't be vary reliable then.

I'm pretty sure there's a way (with escape codes) to reposition the shell cursor to the upper right of the screen. If either of you are still up for this, biome could stick the current environment in the upper right instead when a shell session starts, and remove it when the session completes.

EDIT: Here's a quick example script I found online that does this: http://www.bashguru.com/2010/04/shell-script-to-display-time-and-date.html

**Comment by joesavage** [comment]
That's certainly another option. An infinite loop that runs in the background to write the correct project identifier to the top of the shell seems a bit heavyweight for a project like this though. It might be a better option to use `PS1`, but with a few shell-specific implementation details.
