### ISSUE TITLE
Allow Biomefiles to start with a dot

### ISSUE THREAD

**Issue by 1egoman** [1egoman/biome#19]
I've gotten a few complaints about `Biomefile`s being visible in the root of a repository when a user runs `ls`. It'd be great if a `Biomefile` could optionally start with a `.`, ie, a `.Biomefile`.

- Make the recursive search bit of the `Biomefile` discovery algorithm (first function in the file) look for `.Biomefile`s as well as `Biomefile`s.
- Write a test or two to confirm that the functionality works.
- Document the ability to use `.Biomefile`s in the helptext ('biome help`) and in the readme.

**Comment by Tushar-Gupta** [comment]
Hi 1egoman,

I'm starting to work on this issue. Will follow the steps mentioned by you and send a pull request if it works.

Thanks!

**Comment by Thomasvdam** [comment]
I figure I should be able to pick this up. 1 question though: in the case that there is a `Biomefile` and a `.Biomefile`, which one should take precedence?

**Comment by 1egoman** [comment]
@Thomasvdam Probably `Biomefile`, since that's what a user would expect.

Thanks for taking this issue up!
