### ISSUE TITLE
Ensure the installation snippet works everywhere.

### ISSUE THREAD

**Issue by 1egoman** [1egoman/biome#23]
Here's what's in the readme right now (as of 10/16/16) to install biome:
```
curl https://raw.githubusercontent.com/1egoman/biome/master/biome.sh > /usr/local/bin/biome && sudo chmod 755 /usr/local/bin/biome
```

The above downloads the latest biome.sh from master and copies it to `/usr/local/bin/biome`, then makes it executable. Sometimes, depending on who owns `/usr/local/bin`, the install snippet that's inside of the readme doesn't work because the currently logged in user doesn't have permission to write to `/usr/local/bin`. Two ideas I had to fix this:

- Maybe install to another directory on the system and add that directory to the `PATH`?
- Use something like `tee` in the above snippet with sudo to bypass the file redirection permissions restrictions.

Thanks for the help!

**Comment by Robiathin** [comment]
How about the following command? See [install(1)](http://man.openbsd.org/install.1) (It's an OpenBSD man page but the install is generally available everywhere on Linux/BSD systems). If that works for you I'll open a pull request to change it in the readme.

```
curl https://raw.githubusercontent.com/1egoman/biome/master/biome.sh > /tmp/biome && sudo install -m 555 /tmp/biome /usr/local/bin
```

**Comment by 1egoman** [comment]
@Robiathin Seems to work for me in macOS - if you're confident this should work in Linux this looks great!

**Comment by Robiathin** [comment]
Awesome! Opening a PR now.
